spring:
  application:
    name: qtty
    version: 0.0.1

  datasource:
    url: jdbc:postgresql://postgres:5432/qtty_db
    username: ${QTTY_APP}
    password: ${QTTY_PASSWORD}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss