spring:
  application:
    name: qtty
    version: 0.0.1

  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/qtty_db
    username: ${QTTY_APP}
    password: ${QTTY_PASSWORD}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss