--
-- PostgreSQL database dump
--

\restrict pRktyZ00zXNnC4Ru40cxlH3juzHBFaYafcOXIoFBKuTA0KRitPNRdnVhEwNgWCU

-- Dumped from database version 18.2 (Debian 18.2-1.pgdg13+1)
-- Dumped by pg_dump version 18.2 (Debian 18.2-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dc_channel; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.dc_channel (
                                   discord_id bigint NOT NULL,
                                   id bigint NOT NULL,
                                   name character varying(255),
                                   type character varying(255),
                                   CONSTRAINT dc_channel_type_check CHECK (((type)::text = ANY ((ARRAY['VOICE'::character varying, 'TEXT'::character varying])::text[])))
);


ALTER TABLE public.dc_channel OWNER TO qtty_app;

--
-- Name: dc_channel_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.dc_channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dc_channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dc_channel_permissions; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.dc_channel_permissions (
                                               id bigint NOT NULL
);


ALTER TABLE public.dc_channel_permissions OWNER TO qtty_app;

--
-- Name: dc_channel_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.dc_channel_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dc_channel_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dc_guild; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.dc_guild (
                                 allowed boolean,
                                 audit_channel_id bigint,
                                 discord_id bigint NOT NULL,
                                 id bigint NOT NULL,
                                 movies_channel_id bigint,
                                 name character varying(255)
);


ALTER TABLE public.dc_guild OWNER TO qtty_app;

--
-- Name: dc_guild_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.dc_guild ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dc_guild_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dc_role; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.dc_role (
                                discord_id bigint NOT NULL,
                                guild_id bigint NOT NULL,
                                id bigint NOT NULL,
                                role_name character varying(255) NOT NULL
);


ALTER TABLE public.dc_role OWNER TO qtty_app;

--
-- Name: dc_role_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.dc_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dc_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movie; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.movie (
                              discord_rating_message_id bigint,
                              id bigint NOT NULL,
                              name character varying(255)
);


ALTER TABLE public.movie OWNER TO qtty_app;

--
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movie_ratings; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.movie_ratings (
                                      movie_id bigint NOT NULL,
                                      ratings_id bigint NOT NULL
);


ALTER TABLE public.movie_ratings OWNER TO qtty_app;

--
-- Name: qtty_user; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.qtty_user (
                                  discord_id bigint NOT NULL,
                                  id bigint NOT NULL,
                                  username character varying(255)
);


ALTER TABLE public.qtty_user OWNER TO qtty_app;

--
-- Name: qtty_user_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.qtty_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qtty_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rating_record; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.rating_record (
                                      rating double precision,
                                      id bigint NOT NULL,
                                      movie_id bigint,
                                      user_id bigint
);


ALTER TABLE public.rating_record OWNER TO qtty_app;

--
-- Name: rating_record_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.rating_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rating_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_guild_profile; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.user_guild_profile (
                                           guild_id bigint,
                                           id bigint NOT NULL,
                                           user_id bigint,
                                           guild_user_nick_name character varying(255)
);


ALTER TABLE public.user_guild_profile OWNER TO qtty_app;

--
-- Name: user_guild_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: qtty_app
--

ALTER TABLE public.user_guild_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_guild_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_guild_profile_roles; Type: TABLE; Schema: public; Owner: qtty_app
--

CREATE TABLE public.user_guild_profile_roles (
                                                 roles_id bigint NOT NULL,
                                                 user_guild_profile_id bigint NOT NULL
);


ALTER TABLE public.user_guild_profile_roles OWNER TO qtty_app;

--
-- Name: dc_channel dc_channel_discord_id_key; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_channel
    ADD CONSTRAINT dc_channel_discord_id_key UNIQUE (discord_id);


--
-- Name: dc_channel_permissions dc_channel_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_channel_permissions
    ADD CONSTRAINT dc_channel_permissions_pkey PRIMARY KEY (id);


--
-- Name: dc_channel dc_channel_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_channel
    ADD CONSTRAINT dc_channel_pkey PRIMARY KEY (id);


--
-- Name: dc_guild dc_guild_discord_id_key; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_guild
    ADD CONSTRAINT dc_guild_discord_id_key UNIQUE (discord_id);


--
-- Name: dc_guild dc_guild_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_guild
    ADD CONSTRAINT dc_guild_pkey PRIMARY KEY (id);


--
-- Name: dc_role dc_role_discord_id_key; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_role
    ADD CONSTRAINT dc_role_discord_id_key UNIQUE (discord_id);


--
-- Name: dc_role dc_role_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_role
    ADD CONSTRAINT dc_role_pkey PRIMARY KEY (id);


--
-- Name: movie movie_discord_rating_message_id_key; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_discord_rating_message_id_key UNIQUE (discord_rating_message_id);


--
-- Name: movie movie_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);


--
-- Name: movie_ratings movie_ratings_ratings_id_key; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.movie_ratings
    ADD CONSTRAINT movie_ratings_ratings_id_key UNIQUE (ratings_id);


--
-- Name: qtty_user qtty_user_discord_id_key; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.qtty_user
    ADD CONSTRAINT qtty_user_discord_id_key UNIQUE (discord_id);


--
-- Name: qtty_user qtty_user_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.qtty_user
    ADD CONSTRAINT qtty_user_pkey PRIMARY KEY (id);


--
-- Name: rating_record rating_record_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.rating_record
    ADD CONSTRAINT rating_record_pkey PRIMARY KEY (id);


--
-- Name: user_guild_profile user_guild_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.user_guild_profile
    ADD CONSTRAINT user_guild_profile_pkey PRIMARY KEY (id);


--
-- Name: rating_record fk3aj53yffqccnhlkqforc4eufp; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.rating_record
    ADD CONSTRAINT fk3aj53yffqccnhlkqforc4eufp FOREIGN KEY (movie_id) REFERENCES public.movie(id);


--
-- Name: movie_ratings fk5j60i2nteicsrt2o3f1bu0c14; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.movie_ratings
    ADD CONSTRAINT fk5j60i2nteicsrt2o3f1bu0c14 FOREIGN KEY (ratings_id) REFERENCES public.rating_record(id);


--
-- Name: user_guild_profile_roles fk8oa6ulpnxvanin7kk9523pfd9; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.user_guild_profile_roles
    ADD CONSTRAINT fk8oa6ulpnxvanin7kk9523pfd9 FOREIGN KEY (roles_id) REFERENCES public.dc_role(id);


--
-- Name: user_guild_profile fka49pnkty08gti7bmkn875iiqh; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.user_guild_profile
    ADD CONSTRAINT fka49pnkty08gti7bmkn875iiqh FOREIGN KEY (guild_id) REFERENCES public.dc_guild(id);


--
-- Name: user_guild_profile fkaym7lp5r6bqcxc2ff8j3r6tik; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.user_guild_profile
    ADD CONSTRAINT fkaym7lp5r6bqcxc2ff8j3r6tik FOREIGN KEY (user_id) REFERENCES public.qtty_user(id);


--
-- Name: dc_role fkd30cy8heqjui9u02ocr42ti8n; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.dc_role
    ADD CONSTRAINT fkd30cy8heqjui9u02ocr42ti8n FOREIGN KEY (guild_id) REFERENCES public.dc_guild(id);


--
-- Name: user_guild_profile_roles fkghju2p4uci2utish3i6b5ka85; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.user_guild_profile_roles
    ADD CONSTRAINT fkghju2p4uci2utish3i6b5ka85 FOREIGN KEY (user_guild_profile_id) REFERENCES public.user_guild_profile(id);


--
-- Name: movie_ratings fkky2b7201ypwxqp3p67int4gkc; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.movie_ratings
    ADD CONSTRAINT fkky2b7201ypwxqp3p67int4gkc FOREIGN KEY (movie_id) REFERENCES public.movie(id);


--
-- Name: rating_record fktr812i1i76p0hay2gwchyh61; Type: FK CONSTRAINT; Schema: public; Owner: qtty_app
--

ALTER TABLE ONLY public.rating_record
    ADD CONSTRAINT fktr812i1i76p0hay2gwchyh61 FOREIGN KEY (user_id) REFERENCES public.qtty_user(id);

